baseURL = 'https://suzuka-chan.moe/'
locale = 'zh-CN'
title = '小凉花厨的网站'
defaultContentLanguage = 'zh-cn'
hasCJKLanguage = true
enableRobotsTXT = true
disableKinds = ['taxonomy']
summaryLength = 90

[pagination]
  pagerSize = 10

[permalinks]
  posts = '/posts/:year/:month/:slug/'

[taxonomies]
  tag = 'tags'
  category = 'categories'

[params]
  description = 'Galgame 感想、偶尔浮现的思考，以及落下的生活碎片。'
  author = 'Suzuka'
  images = ['favicon/favicon-orb.png']

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
    [markup.goldmark.renderer]
      unsafe = false
  [markup.highlight]
    noClasses = false
    lineNos = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false
